modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "${description}"
logoFile = "${icon}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "${loader_version_neoforge}"
ordering = "NONE"
side = "BOTH"
